FROM docker.io/almalinux/9-minimal:latest
LABEL source="https://github.com/herzeleid02/containerfiles"

# its hardcoded but whatever... well figure out something
#ARG jarname="better-than-adventure-7.1.Prerelease.1a-server.jar"

RUN 'echo "install_weak_deps=False" >> /etc/dnf/dnf.conf'
RUN 'dnf install java-1.8.0-openjdk-headless'

RUN 'mkdir /opt/minecraft-bta-server'

RUN 'curl -O https://github.com/Better-than-Adventure/bta-download-repo/releases/download/v7.1-prerelease-1a/better-than-adventure-7.1.Prerelease.1a-server.jar --output-dir /opt/'

WORKDIR "/opt/minecraft-bta-server/"

ENTRYPOINT ["java -jar /opt/better-than-adventure-7.1.Prerelease.1a-server.jar"]

